module.exports = [
  `https://www.svtplay.se/api/latest?page={page}&pageSize={pageSize}`,
  `https://www.svtplay.se/api/recommended`,
  `https://www.svtplay.se/api/popular?page={page}&pageSize={pageSize}`,
  `https://www.svtplay.se/api/last_chance?page={page}&pageSize={pageSize}`,
  `https://www.svtplay.se/api/live?page={page}&pageSize={pageSize}`,
  `https://www.svtplay.se/api/clusters`,
  `https://www.svtplay.se/api/all_titles_and_singles`,
  `https://www.svtplay.se/api/program_guide?channel={channel}&from={from}&to={to}`,
  `https://www.svtplay.se/api/channel_page?now={now}`,
  `https://www.svtplay.se/api/server_time`,
  `https://www.svtplay.se/api/search_autocomplete_list`,
  [ `video`, `http://api.svt.se/videoplayer-api/video/{id}` ],
  `https://www.svtplay.se/api/title_by_episode?id={articleId}`,
  `https://www.svtplay.se/api/episode?id={articleId}`,
  `https://www.svtplay.se/api/highlights?articleId={articleId}`,
  `https://www.svtplay.se/api/title_episodes_by_episode_article_id?articleId={articleId}`,
  `https://www.svtplay.se/api/title_clips_by_episode_article_id?articleId={articleId}`,
  `https://www.svtplay.se/api/upcoming_episodes_by_title_article_id?articleId={articleId}`,
  `https://www.svtplay.se/api/similar_content_for_episode?id={id}`,
  `https://www.svtplay.se/api/important_messages`,
  `https://www.svtplay.se/api/title?slug={slug}`,
  [ `channel`, `https://api.svt.se/videoplayer-api/video/ch-{channel}` ]
]
